version: '3.8'
services:
  postgres:
    image: postgres
    container_name: cloudi_p
    environment:
      POSTGRES_PASSWORD: root123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: cloudi_a
    ports:
      - 8082:8080
    depends_on:
      - postgres

volumes:
  db_data:
  minio_data:
